"""CONSTANTS SPECIFIED HERE."""
FOLLOW_USERS = "follow_users"
USERS = "users"
HEADER = "header"
ID = "id"
COOKIE = "Cookie"
URL = "url"
BODY = "body"
JSON = "json"
DATA = "data"
NEXT = "next"
VARIABLES = "variables"
VARIABLES = "variables"
USER_NAME = "username"
PAGING = "paging"
PAGING_INFO = "pagingInfo"
FROM = "from"
LOADING = "loading"
USER_RESULT = "userResult"
FOLLOWING_USERS_CONNECTIONS = "followingUserConnection"
FOLLOWERS_USERS_CONNECTIONS = "followersUserConnection"
USER_FOLLOWED_WITH_ID = "Followed user with ID:"
ALREADY_FOLLOWED_YOU = "Already Followed you"
DATA_FETCHING_COMPLETED = "Data fetching completed"
COUNT_FOLLOWED_USERS = "Total target users followed"
FETCH_FOLLOWING_LIST = "fetch_following_list"
FETCH_FOLLOWERS_LIST = "fetch_followers_list"

ERROR_LIMIT_EXCEEDED = "Follow limit reached. Exiting."
ERROR_IN_DECODING_FILE = "Error decoding JSON file"
ERROR_IN_WRITING_FILE = "Error writing to file"
ERROR_FAILED_WITH_ERROR = "Request failed with error"
ERROR_FAILED_WITH_STATUS_CODE = "Request failed with status code"
ERROR_KEY_NOT_FOUND = "Key not found in JSON data."
ERROR_NONE_API_RESPONSE = "Error: API response is None"

INPUT_USERNAME = "Enter Your Username:"
INPUT_TARGET_USERNAME = "Enter Target Username:"
INPUT_UNIQUE_TOKEN = "Enter Your Unique Token:"
INPUT_IS_PREVIOUS_TOKEN = "Want to use Previous token (yes/no) :"

PATH_UNIQUE_HEADER_FILE = "data/unique_header.json"
PATH_DEFAULT_JSON_FILE_READER = "secret/json/config.json"
PATH_USER_FILE = "data/my_followers.json"
PATH_TARGET_FILE = "data/target_followers.json"
